@echo off
chcp 65001 >nul
title KARMA OP TWEAKS
color 3

:banner
echo.
echo ██ ▄█▀▄▄▄       ██▀███   ███▄ ▄███▓ ▄▄▄         ▄▄▄█████▓ █     █░▓█████ ▄▄▄       ██ ▄█▀  ██████ 
echo ██▄█▒▒████▄    ▓██ ▒ ██▒▓██▒▀█▀ ██▒▒████▄       ▓  ██▒ ▓▒▓█░ █ ░█░▓█   ▀▒████▄     ██▄█▒ ▒██    ▒ 
echo ▓███▄░▒██  ▀█▄  ▓██ ░▄█ ▒▓██    ▓██░▒██  ▀█▄     ▒ ▓██░ ▒░▒█░ █ ░█ ▒███  ▒██  ▀█▄  ▓███▄░ ░ ▓██▄   
echo ▓██ █▄░██▄▄▄▄██ ▒██▀▀█▄  ▒██    ▒██ ░██▄▄▄▄██    ░ ▓██▓ ░ ░█░ █ ░█ ▒▓█  ▄░██▄▄▄▄██ ▓██ █▄   ▒   ██▒
echo ▒██▒ █▄▓█   ▓██▒░██▓ ▒██▒▒██▒   ░██▒ ▓█   ▓██▒     ▒██▒ ░ ░░██▒██▓ ░▒████▒▓█   ▓██▒▒██▒ █▄▒██████▒▒
echo ▒ ▒▒ ▓▒▒▒   ▓▒█░░ ▒▓ ░▒▓░░ ▒░   ░  ░ ▒▒   ▓▒█░     ▒ ░░   ░ ▓░▒ ▒  ░░ ▒░ ░▒▒   ▓▒█░▒ ▒▒ ▓▒▒ ▒▓▒ ▒ ░
echo ░ ░▒ ▒░ ▒   ▒▒ ░  ░▒ ░ ▒░░  ░      ░  ▒   ▒▒ ░       ░      ▒ ░ ░   ░ ░  ░ ▒   ▒▒ ░░ ░▒ ▒░░ ░▒  ░ ░
echo ░ ░░ ░  ░   ▒     ░░   ░ ░      ░     ░   ▒        ░        ░   ░     ░    ░   ▒   ░ ░░ ░ ░  ░  ░  
echo ░  ░        ░  ░   ░            ░         ░  ░                ░       ░  ░     ░  ░░  ░         ░ 
timeout 3 >nul
echo ...
timeout 3 >nul
echo ...
timeout 3 >nul
echo ...
timeout 3 >nul
echo ...
timeout 3 >nul
cls 
timeout 3 >nul
echo The Tweaks Have Succesfully Started!
timeout 3 >nul
echo ...
echo Waiting on less latency feature...
timeout 3 >nul
echo ...
echo Success!
timeout 3 >nul
echo ...
echo Adding all other latency remover's...
timeout 3 >nul
echo ...
echo Added!
timeout 3 >nul
echo ...
echo Optimizing network usage...
timeout 3 >nul
echo ...
echo Success!
timeout 3 >nul
echo ...
echo Your PC Is At It's Full Rate Limit. Try Deleting Some Games...
timeout 3 >nul
echo ...
echo Closing program in 3 second's... 
timeout 3 >nul
echo ...
pause >nul
exit
